#!/bin/bash -e
################################################################################
# Script to set up Debian Linux.
# Execute this script as superuser.
################################################################################

# Update to the latest stable release
CODENAME=bookworm
  
# Select desktop environment, defaulting to GNOME
DE="$1"
case $DE in
  xfce)
    ;;
  *)
    DE=gnome
    ;;
esac
# Set up Debian's official repos
echo "deb https://deb.debian.org/debian/ $CODENAME main contrib non-free non-free-firmware
deb https://deb.debian.org/debian/ $CODENAME-updates main contrib non-free
deb https://deb.debian.org/debian-security/ $CODENAME-security main contrib non-free
deb https://deb.debian.org/debian/ $CODENAME-backports main contrib non-free" > /etc/apt/sources.list
apt-get update
apt-get -y dist-upgrade

# Install some core utilities
apt-get -y install ansible curl git

# Set up Tailscale
curl -fsSL https://tailscale.com/install.sh | bash

# Harmonise theming for QT and GTK apps
echo "QT_STYLE_OVERRIDE=gtk" > /etc/environment

# Configure boot behaviour
sed -i "s/GRUB_TIMEOUT=\d+/GRUB_TIMEOUT=0/" /etc/default/grub
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="splash quiet"/' /etc/default/grub
update-grub2

# Hand over to ansible
ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-$DE.yml
