#!/bin/bash -e
################################################################################
# Script to set up Debian Linux.
# Execute this script as superuser.
################################################################################

CODENAME=trixie

# Set up Debian's official repos
echo "deb https://deb.debian.org/debian/ $CODENAME main contrib non-free non-free-firmware
deb https://security.debian.org/debian-security/ $CODENAME-security main contrib non-free
deb https://deb.debian.org/debian/ $CODENAME-updates main contrib non-free
deb https://deb.debian.org/debian/ $CODENAME-backports main contrib non-free" > /etc/apt/sources.list

# Set up Mozilla Firefox repo
curl -fsSL "https://packages.mozilla.org/apt/repo-signing-key.gpg" | gpg --dearmor -o "/usr/share/keyrings/firefox-archive-keyring.gpg"
echo "deb [signed-by=/usr/share/keyrings/firefox-archive-keyring.gpg] https://packages.mozilla.org/apt mozilla main" | tee /etc/apt/sources.list.d/firefox.list

# Set up VirtualBox repo
VBOXVERSION=7.1
wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $CODENAME contrib" > /etc/apt/sources.list.d/virtualbox.list

# Update system
apt -y modernize-sources
apt-get update
apt-get -y dist-upgrade

# Install some core utilities
apt-get -y install \
  ansible \
  docker.io \
  docker-compose \
  git \
  unattended-upgrades

# Set up Tailscale
curl -fsSL https://tailscale.com/install.sh | bash

# Configure boot behaviour
sed -i "s/GRUB_TIMEOUT=\d+/GRUB_TIMEOUT=0/" /etc/default/grub
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="splash quiet"/' /etc/default/grub
update-grub2

# Install custom scripts
curl -fsSL https://raw.githubusercontent.com/ngkengwooi/desktop-config/main/scripts/system-update -o /usr/local/sbin/system-update
curl -fsSL https://raw.githubusercontent.com/ngkengwooi/desktop-config/main/scripts/nextcloud-folders -o /usr/local/bin/nextcloud-folders
chmod +x /usr/local/bin/* /usr/local/sbin/*

# Final system update
apt -y modernize-sources
system-update
