- hosts: localhost
  become: true
  tasks:
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - adwaita-qt6
        - ffmpeg
        - filezilla
        - firefox
        - firmware-b43-installer
        - firmware-linux-nonfree
        - flatpak
        - gimp
        - gnome-core
        - gnome-shell-extension-caffeine        
        - gnome-software-plugin-flatpak
        - grsync
        - ibus-libpinyin
        - inkscape
        - lame
        - malcontent
        - musescore3
        - openssh-server
        - pdfarranger
        - puddletag
        - python3-pip
        - qgnomeplatform-qt5
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - qt6-gtk-platformtheme   
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - ttf-mscorefonts-installer
        - unattended-upgrades
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - chromium
        - firefox-esr
        - synaptic
        - transmission-gtk
        - zutty
      state: absent
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
