- hosts: localhost
  become: true
  tasks:
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - adwaita-qt6
        - dialect
        - ffmpeg
        - filezilla
        - flatpak
        - fonts-crosextra-caladea
        - fonts-crosextra-carlito
        - gimp
        - gnome-core
        - gnome-remote-desktop
        - gnome-software-plugin-flatpak
        - gnome-tweaks
        - htop
        - ibus-libpinyin
        - inkscape
        - lame
        - libreoffice
        - libreoffice-gnome
        - libreoffice-java-common
        - malcontent
        - openssh-server
        - pdfarranger
        - pipx
        - qgnomeplatform-qt5
        - qgnomeplatform-qt6
        - qt5-gtk-platformtheme
        - qt6-gtk-platformtheme   
        - remmina
        - ttf-mscorefonts-installer
        - unattended-upgrades
      state: latest

  - name: Uninstall packages
    package:
      name:
        - cheese
        - firefox-esr
        - freecad
        - gufw
        - lutris
        - prusa-slicer
        - rhythmbox
        - synaptic
        - transmission-gtk
      state: absent
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present

  - name: Install flatpaks
    community.general.flatpak:
      name:
        - com.bitwarden.desktop
        - org.chromium.Chromium
        - org.localsend.localsend_app
        - org.mozilla.firefox
        - org.zotero.Zotero
      state: latest   
